language: ruby
rvm:
  - 2.5.1

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --assume-extension ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler
sudo: false

notifications:
  email:
    on_success: change #  default: change
    on_failure: always # default: always
