language: ruby
rvm:
  - 2.5.1

before_script:
 - chmod +x ./script/cibuild

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

script: ./script/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler
sudo: false
